# POST http://localhost:5000/api/new-quote
# Content-Type: application/json

# {
#   "quote": "It's da best. I looooove it.",
#   "author": "Nacho Libre"
# }

# GET http://localhost:5000/api/quotes
GET http://localhost:5000/api/quote/31
# PUT http://localhost:5000/api/update/31
# Content-Type: application/json

# {
#   "quote": "It's fant-TAS-tic!"
# }